# Pytorch 101 - Deep Learning from Zero to GAN

### Excercise 1

An short introduction about PyTorch and about the chosen functions. 
- torch.eye
- torch.sparse
- torch.argmax()
- torch.argsort()
- torch.reshape

In [1]:
# Import torch and other required modules
import torch

## Function 1 - torch.eye

This function can be used in many matrix calculations wherein we can incorporate identity matrix to enable the matrix operation and convert the resulting matrix dimensions.

In [2]:
# the identity matrix having dimension (5,5) with values 1
a = 1 * torch.eye(5)
a

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [3]:
b = 4 * torch.eye(-1)
b

RuntimeError: n must be greater or equal to 0, got -1

torch.eye tensor function only accepts the size greater or equal to 0

In [4]:
# the identity matrix having dimension (7,7) with values 3
c = 3 * torch.eye(7)
c

tensor([[3., 0., 0., 0., 0., 0., 0.],
        [0., 3., 0., 0., 0., 0., 0.],
        [0., 0., 3., 0., 0., 0., 0.],
        [0., 0., 0., 3., 0., 0., 0.],
        [0., 0., 0., 0., 3., 0., 0.],
        [0., 0., 0., 0., 0., 3., 0.],
        [0., 0., 0., 0., 0., 0., 3.]])

## Function 2 - torch.sparse

Torch can create sparse tensors which can efficiently be used to store and process the tensors for which majority of the values are zero. This function can be used in the recommender system engine where majority of the explicit ratings are not given and thus we can create a sparse tensor matrix which can reduce the data size and performs much faster calculations.

In [5]:
i = torch.LongTensor([[0, 1, 1],
                      [2, 0, 2]])
v = torch.FloatTensor([3, 4, 5])

torch.sparse.FloatTensor(i, v, torch.Size([2,3])).to_dense()

tensor([[0., 0., 3.],
        [4., 0., 5.]])

A sparse tensor can be created by providing a 2D tensor of indices (i), a tensor of values (v) and the size of the sparse tensor.

### More example.

The below example does matrix multiplication of sparse matrix with the dense tensor matrix

In [6]:
# Sparse matric
a = torch.randn(2, 3).to_sparse().requires_grad_(True)
a

tensor(indices=tensor([[0, 0, 0, 1, 1, 1],
                       [0, 1, 2, 0, 1, 2]]),
       values=tensor([-1.4151, -1.8183, -0.2498,  0.5613, -0.3937,  0.4011]),
       size=(2, 3), nnz=6, layout=torch.sparse_coo, requires_grad=True)

In [7]:
# dense tensor matrix
b = torch.randn(3, 2, requires_grad=True)
b

tensor([[ 0.6819, -0.9821],
        [ 0.3490,  1.7299],
        [ 0.4486,  1.0758]], requires_grad=True)

In [8]:
# Matrix multiplication
y = torch.sparse.mm(a, b)
y

tensor([[-1.7117, -2.0242],
        [ 0.4253, -0.8009]], grad_fn=<SparseAddmmBackward>)

In [9]:
y.sum()

tensor(-4.1115, grad_fn=<SumBackward0>)

## Function 3 - torch.argmax()

This function returns the index of maximum tensor element.

In [10]:
# this function will create a normally distributed random numbers having mean 0 and variance 1
rand_numbers = torch.randn(2, 3)
rand_numbers

tensor([[ 0.5100, -0.0575, -0.1829],
        [ 1.3792,  0.2071, -0.3934]])

In [11]:
# this function returns the index of maximum tensor element value
torch.argmax(rand_numbers)

tensor(3)

In [12]:
# returns the index of maximum tensor element row-wise
torch.argmax(rand_numbers, dim = 1)

tensor([0, 0])

In [13]:
# returns the index of maximum tensor element column-wise
torch.argmax(rand_numbers, dim = 0)

tensor([1, 1, 0])

## Function 4 - torch.argsort()

This function sort the index of the tensor element in the ascending order by default.

In [14]:
torch.argsort(rand_numbers, dim = 1)

tensor([[2, 1, 0],
        [2, 1, 0]])

In order to sort the index of tensor element in descending order

In [15]:
# Row-wise index sort
torch.argsort(rand_numbers, dim = 1, descending = True)

tensor([[0, 1, 2],
        [0, 1, 2]])

In [16]:
# Column-wise index sort
torch.argsort(rand_numbers, dim = 0, descending = True)

tensor([[1, 1, 0],
        [0, 0, 1]])

## Function 5 - torch.reshape

This tensor function takes tensor as a input and converts/reshapes the size of the input tensor without changing the tensor values.

In [17]:
### Example 1 - working
x = torch.randn(6)
torch.reshape(x, (2, 3))

tensor([[ 1.5699,  1.5607,  2.3157],
        [-0.5689,  0.2987, -1.1312]])

Reshape an input 1D array to 2 by 3 dimensions.

In [18]:
# Example 2 - working
y = torch.tensor([[[1,2,3.], [6,3,10],
                   [4,4,5], [1,1,2]],
                   [[0,2,3.], [1,6,7],
                   [2,4,3], [2,2,2]]])
torch.reshape(y, (-1,))

tensor([ 1.,  2.,  3.,  6.,  3., 10.,  4.,  4.,  5.,  1.,  1.,  2.,  0.,  2.,
         3.,  1.,  6.,  7.,  2.,  4.,  3.,  2.,  2.,  2.])

Reshape an input tensor of size 2,2,3 to size 1.

In [19]:
# Example 3 - breaking (to illustrate when it breaks)
y = torch.arange(5.)
torch.reshape(y, (2, 4))

RuntimeError: shape '[2, 4]' is invalid for input of size 5

The function reshape did not work because the tensor size was 5 and function expected size of 2 by 4.

This function can help in the image size transformation.

## Conclusion

This is just the basic pytorch functions covered in this notebook. For more please checkout the reference link.

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for `torch.Tensor`: https://pytorch.org/docs/stable/tensors.html

In [20]:
!pip install jovian --upgrade --quiet

In [21]:
import jovian

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Please enter your API key ( from https://jovian.ml/ ):
API KEY: 